In [1]:
import numpy as np

In [ ]:
# 
0D - Scalar - 
1D - 1D vector - list,tuple
2D - 2D vector - rows and columns
3D - 3D vector - rows and columns and dept


# It is an homogenous 
# Numpy - numerical operations 
[] --> 1D
[[], []] --> 2D
[[],[],[],[]] --->2D
[[[],[]],[[],[]]]  --> 3D


Array --> matrices


In [5]:
 # 
lst = [1,32,4,45,5,6]

arr = np.array(lst)

print(arr, type(arr))


# Shape
print(arr.shape)

# Size
print(arr.size)

# Dim
print(arr.ndim)


[ 1 32  4 45  5  6] <class 'numpy.ndarray'>
(6,)
6
1


In [8]:
 # 2D
lst = [[1,2,3,4],[1,2,4,5]]

arr = np.array(lst)

print(arr, type(arr))


# Shape
print(arr.shape)

# Size
print(arr.size)

# Dim
print(arr.ndim)


[[1 2 3 4]
 [1 2 4 5]] <class 'numpy.ndarray'>
(2, 4)
8
2


In [17]:
 # 3D
lst = [[[1,32],[2,4]],[[4,56],[7,6]]]

arr = np.array(lst)

print(arr, type(arr))


# Shape
print(arr.shape)

# Size
print(arr.size)

# Dim
print(arr.ndim)


[[[ 1 32]
  [ 2  4]]

 [[ 4 56]
  [ 7  6]]] <class 'numpy.ndarray'>
(2, 2, 2)
8
3


In [9]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [21]:
# zeros and zero-like

np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
lst = [[[1,32],[2,4]],[[4,56],[7,6]]]

arr = np.array(lst)


np.zeros_like(arr)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [23]:
# Arange

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr_2 = np.arange(25)
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
# ones like
# (1,0)
# (25,)

np.ones_like(arr_2).shape

(25,)

In [43]:
arr_3 = np.arange(36).reshape(6,6)

In [44]:
# 6,6
arr_3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
np.ones_like(arr_3)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [46]:
arr_3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
ide = np.eye(6,7)

In [57]:
ide

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [58]:
ide.shape

(6, 7)

In [80]:
# create an array with random

np.random.rand(1,6) # std---> 

array([[0.25906706, 0.29874302, 0.84175268, 0.97770308, 0.11310888,
        0.76548485]])

In [77]:
# Ludo
np.random.randint(1,7)

5

In [79]:
np.random.randn(1,6)

array([[ 0.25660563, -0.57177197, -1.11779451,  0.02984387, -0.54483379,
        -0.01351832]])

# Reshaping the array

In [82]:
a = np.arange(6)

print(a.shape)
print(a.size)
print(a.ndim)
print(a)

(6,)
6
1
[0 1 2 3 4 5]


In [87]:
# Change the shape of a 

a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
# Change the shape of a 

a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
# np.arange(13).reshape()

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [97]:
np.arange(12).reshape(2,3,2,1,1,1,1,1,1)

array([[[[[[[[[ 0]]]]]],





         [[[[[[ 1]]]]]]],






        [[[[[[[ 2]]]]]],





         [[[[[[ 3]]]]]]],






        [[[[[[[ 4]]]]]],





         [[[[[[ 5]]]]]]]],







       [[[[[[[[ 6]]]]]],





         [[[[[[ 7]]]]]]],






        [[[[[[[ 8]]]]]],





         [[[[[[ 9]]]]]]],






        [[[[[[[10]]]]]],





         [[[[[[11]]]]]]]]])

In [99]:
np.arange(36).reshape(6,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [111]:
# 

asian_countries = np.array(['India', 'China', 'pakistan','korea','bangladesh','taiwan','japan','bhutan'])

asian_countries

array(['India', 'China', 'pakistan', 'korea', 'bangladesh', 'taiwan',
       'japan', 'bhutan'], dtype='<U10')

In [ ]:
# C

unistring - u
10 --. all the string is less than the len of 10

In [109]:
asian_countries.reshape(2,2,2)

array([[['India', 'China'],
        ['pakistan', 'korea']],

       [['bangladesh', 'taiwan'],
        ['japan', 'bhutan']]], dtype='<U10')

In [112]:
# infer 

arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
arr_1.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
np.arange(50).reshape(10,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [119]:
np.arange(50).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [123]:
np.arange(36).reshape(2,3,-1)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [124]:
np.arange(36).reshape(-1,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [125]:
np.arange(36).reshape(-1,-1,2)

ValueError: can only specify one unknown dimension

In [135]:
np.arange(10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Transpose

In [ ]:
# (2*3)  ---> (3*2)

In [136]:
a = np.arange(10).reshape(2,5)

In [137]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [139]:
num = np.arange(36).reshape(2,3,6)
num

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [140]:
num.T

array([[[ 0, 18],
        [ 6, 24],
        [12, 30]],

       [[ 1, 19],
        [ 7, 25],
        [13, 31]],

       [[ 2, 20],
        [ 8, 26],
        [14, 32]],

       [[ 3, 21],
        [ 9, 27],
        [15, 33]],

       [[ 4, 22],
        [10, 28],
        [16, 34]],

       [[ 5, 23],
        [11, 29],
        [17, 35]]])

In [143]:
a = np.arange(10)


# Ravel
# Flatten

In [155]:
arr= np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [145]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [147]:
arr= np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [148]:
for i in arr:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]


In [149]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9


In [159]:
arr= np.arange(12).reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [153]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [163]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [161]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [162]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [164]:
for i in arr.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


Differences between Flatten() and Ravel()

a.ravel():
(i) Return only reference/view of original array
(ii) If you modify the array you would notice that the value of original array also changes.
(iii) Ravel is faster than flatten() as it does not occupy any memory.
(iv) Ravel is a library-level function.

a.flatten() :
(i) Return copy of original array
(ii) If you modify any value of this array value of original array is not affected.
(iii) Flatten() is comparatively slower than ravel() as it occupies memory.
(iv) Flatten is a method of an ndarray object.


In [165]:
# Arithmetic operation on array element wise

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

In [166]:
a+b

array([11, 22, 33, 44, 55])

In [167]:
a-b

array([ -9, -18, -27, -36, -45])

In [168]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [169]:
a

array([1, 2, 3, 4, 5])

In [170]:
a/b

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [171]:
a * b

array([ 10,  40,  90, 160, 250])

In [172]:
a > 2

array([False, False,  True,  True,  True])

In [173]:
a

array([1, 2, 3, 4, 5])

In [175]:
sum(a > 2)

3

In [174]:
sum(a)

15

In [178]:
data = np.arange(36).reshape(6,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [181]:
# Matrix multiplication
# 2*3
# 3*2
# 2*2

a = np.array([[1,2,3],[5,6,7]]) # 2*3
b = np.array([[1,4],[5,6],[8,10]])

In [182]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [183]:
b

array([[ 1,  4],
       [ 5,  6],
       [ 8, 10]])

In [184]:
a.dot(b)

array([[ 35,  46],
       [ 91, 126]])

# Unary operation

In [196]:
a = [1,2,32,4,45]
b = ['a','b','c','d','e']
c = [3,4,5,6,7]

In [186]:
di = {'a':1,'b':2,'c':32,'d':4,'e':45}
di

{'a': 1, 'b': 2, 'c': 32, 'd': 4, 'e': 45}

In [197]:
dic_2 = dict(zip(b,a))
dic_2

{'a': 1, 'b': 2, 'c': 32, 'd': 4, 'e': 45}

In [198]:
dic_3 = dict(zip(dic_2,c))
dic_3

{'a': 3, 'b': 4, 'c': 5, 'd': 6, 'e': 7}

In [204]:
inputUser = [10,21,22,98,87,45,33,1,2,100]


for i in inputUser:
    print(i)
    if i%2 == 0:
       inputUser.remove(i)


10
22
87
45
33
1
2


In [206]:
#Write a Python program which takes a list of numbers as input and prints a new list after removing even numbers from it.
#Input:- [10,21,22,98,87,45,33,1,2,100]
#Output:- [21,87,45,33,1]


lst = [10,21,22,98,87,45,33,1,2,100]
out_list = filter(lambda x: True if x%2 != 0 else False , lst)

list(out_list)

[21, 87, 45, 33, 1]

In [209]:
ls=[10,21,22,98,87,45,33,1,2,100]
ls1=[]
for i in ls:
    if i%2!=0:
        ls1.append(i)
        
print(ls1)


[21, 87, 45, 33, 1]


In [207]:
# Initialize dictionary with default values. Inputs are:-
employees = ['Kelly', 'Emma', 'John']
defaults = {"designation": 'Application Developer', "salary": 8000}


dict(zip(employees , defaults))

{'Kelly': 'designation', 'Emma': 'salary'}

In [208]:
employees = ['Kelly', 'Emma', 'John']
defaults = {"designation": 'Application Developer', "salary": 8000}

res = dict()
for i in employees:
    res[i] = defaults
    
res


{'Kelly': {'designation': 'Application Developer', 'salary': 8000},
 'Emma': {'designation': 'Application Developer', 'salary': 8000},
 'John': {'designation': 'Application Developer', 'salary': 8000}}

In [210]:
outputEmp={}
employees = ['Kelly', 'Emma', 'John']
defaults = {"designation": 'Application Developer', "salary": 8000}
for ky in employees:
    outputEmp[ky]=defaults

print(outputEmp)


{'Kelly': {'designation': 'Application Developer', 'salary': 8000}, 'Emma': {'designation': 'Application Developer', 'salary': 8000}, 'John': {'designation': 'Application Developer', 'salary': 8000}}


In [211]:
a = [1,2,3]
b = ['c','b','d']
c = [4,5,6]
d = list(zip(a,c))
e = dict(zip(b,d))
e


{'c': (1, 4), 'b': (2, 5), 'd': (3, 6)}